{ pkgs, lib, config, ... }:
{
  # Auto-created image pull service
  systemd.services."pull-glances-glances-latest-full-image" = {
    description = "Pull latest glances:latest-full image for glances";
    path = [ pkgs.podman ];
    script = ''
      podman pull nicolargo/glances:latest-full
    '';
    serviceConfig = {
      Type = "oneshot";
    };
    wantedBy = [ "multi-user.target" ];
  };


  # Auto-created activation script to pull container images on rebuild
  system.activationScripts.pullglancesContainers = ''
    /run/current-system/sw/bin/echo "Pulling latest image for glances/glances..."
    ${pkgs.podman}/bin/podman pull nicolargo/glances:latest-full || true
    /run/current-system/sw/bin/echo "Done pulling for glances/glances."
    
  '';
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."glances-monitoring" = {
    image = "nicolargo/glances:latest-full";
    environment = {
      "GLANCES_OPT" = "-w";
    };
    volumes = [
      "/run/podman/podman.sock:/var/run/docker.sock:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-glances-monitoring" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "podman-compose-glances-root.target"
    ];
    wantedBy = [
      "podman-compose-glances-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-glances-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
