---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - data:/config
      - /mnt/syno/videos/movies:/movies
      - /mnt/syno/downloads:/downloads
    restart: unless-stopped
    network_mode: host

volumes:
  data:
    driver: local