{ pkgs, lib, config, ... }:
{
  # Auto-created directory rules
  systemd.tmpfiles.rules = [
    "d /var/lib/containers/storage/volumes/sabnzbd/data 0755 root root - -"
  ];
  # Auto-created image pull service
  systemd.services."pull-sabnzbd-sabnzbd-latest-image" = {
    description = "Pull latest sabnzbd:latest image for sabnzbd";
    path = [ pkgs.podman ];
    script = ''
      podman pull lscr.io/linuxserver/sabnzbd:latest
    '';
    serviceConfig = {
      Type = "oneshot";
    };
    wantedBy = [ "multi-user.target" ];
  };


  # Auto-created service to ensure volume directories exist before container start
  systemd.services."ensure-sabnzbd-volumes" = {
    description = "Ensure volume directories exist for sabnzbd";
    after = [ "systemd-tmpfiles-setup.service" ];
    before = [ "podman-sabnzbd.service" ];
    requiredBy = [ "podman-sabnzbd.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.bash}/bin/bash -c \"mkdir -p /var/lib/containers/storage/volumes/sabnzbd/data; \"";
    };
  };


  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."sabnzbd" = {
    image = "lscr.io/linuxserver/sabnzbd:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/UTC";
    };
    volumes = [
      "/var/lib/containers/storage/volumes/sabnzbd/data:/config:rw"
      "/mnt/syno/downloads:/downloads:rw"
      "/mnt/syno/downloads/incomplete:/incomplete-downloads:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-sabnzbd" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "podman-compose-sabnzbd-root.target"
    ];
    wantedBy = [
      "podman-compose-sabnzbd-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-sabnzbd-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
