---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - ./data:/config
      - /mnt/syno/downloads:/downloads
      - /mnt/syno/downloads/incomplete:/incomplete-downloads
    restart: unless-stopped
    network_mode: host

volumes:
  data: