{ pkgs, lib, config, ... }:
{
  # Auto-created directory rules
  systemd.tmpfiles.rules = [
    "d /var/lib/containers/storage/volumes/scrutiny/config 0755 root root - -"
    "d /var/lib/containers/storage/volumes/scrutiny/influxdb 0755 root root - -"
  ];
  # Auto-created image pull service
  systemd.services."pull-scrutiny-scrutiny-master-omnibus-image" = {
    description = "Pull latest scrutiny:master-omnibus image for scrutiny";
    path = [ pkgs.podman ];
    script = ''
      podman pull ghcr.io/analogj/scrutiny:master-omnibus
    '';
    serviceConfig = {
      Type = "oneshot";
    };
    wantedBy = [ "multi-user.target" ];
  };


  # Auto-created activation script to pull container images on rebuild
  system.activationScripts.pullscrutinyContainers = ''
    /run/current-system/sw/bin/echo "Pulling latest image for scrutiny/scrutiny..."
    ${pkgs.podman}/bin/podman pull ghcr.io/analogj/scrutiny:master-omnibus || true
    /run/current-system/sw/bin/echo "Done pulling for scrutiny/scrutiny."
    
  '';
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."scrutiny" = {
    image = "ghcr.io/analogj/scrutiny:master-omnibus";
    volumes = [
      "/var/lib/containers/storage/volumes/scrutiny/config:/opt/scrutiny/config:rw"
      "/var/lib/containers/storage/volumes/scrutiny/influxdb:/opt/scrutiny/influxdb:rw"
      "/run/udev:/run/udev:ro"
    ];
    ports = [
      "8080:8080/tcp"
      "8086:8086/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=SYS_RAWIO"
      "--device=/dev/sda:/dev/sda:rwm"
      "--network-alias=scrutiny"
      "--network=scrutiny_default"
    ];
  };
  systemd.services."podman-scrutiny" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-scrutiny_default.service"
    ];
    requires = [
      "podman-network-scrutiny_default.service"
    ];
    partOf = [
      "podman-compose-scrutiny-root.target"
    ];
    wantedBy = [
      "podman-compose-scrutiny-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-scrutiny_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f scrutiny_default";
    };
    script = ''
      podman network inspect scrutiny_default || podman network create scrutiny_default
    '';
    partOf = [ "podman-compose-scrutiny-root.target" ];
    wantedBy = [ "podman-compose-scrutiny-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-scrutiny-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
