{ pkgs, lib, config, ... }:
{
  # Auto-created image pull service
  systemd.services."pull-sonarr-sonarr-latest-image" = {
    description = "Pull latest sonarr:latest image for sonarr";
    path = [ pkgs.podman ];
    script = ''
      podman pull lscr.io/linuxserver/sonarr:latest
    '';
    serviceConfig = {
      Type = "oneshot";
    };
    wantedBy = [ "multi-user.target" ];
  };


  # Auto-created activation script to pull container images on rebuild
  system.activationScripts.pullsonarrContainers = ''
    /run/current-system/sw/bin/echo "Pulling latest image for sonarr/sonarr..."
    ${pkgs.podman}/bin/podman pull lscr.io/linuxserver/sonarr:latest || true
    /run/current-system/sw/bin/echo "Done pulling for sonarr/sonarr."
    
  '';
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."sonarr" = {
    image = "lscr.io/linuxserver/sonarr:latest";
    environment = {
      "PGID" = "0";
      "PUID" = "0";
      "TZ" = "America/New_York";
    };
    volumes = [
      "/mnt/syno/sonarr/downloads:/downloads:rw"
      "/mnt/syno/sonarr/tv:/tv:rw"
      "sonarr_data:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."podman-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-volume-sonarr_data.service"
    ];
    requires = [
      "podman-volume-sonarr_data.service"
    ];
    partOf = [
      "podman-compose-sonarr-root.target"
    ];
    wantedBy = [
      "podman-compose-sonarr-root.target"
    ];
  };

  # Volumes
  systemd.services."podman-volume-sonarr_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect sonarr_data || podman volume create sonarr_data --driver=local
    '';
    partOf = [ "podman-compose-sonarr-root.target" ];
    wantedBy = [ "podman-compose-sonarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-sonarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
