#!/usr/bin/env bash
set -euo pipefail

# Enable debugging output (set DEBUG=false to disable)
DEBUG=true
if $DEBUG; then
  echo "DEBUG: Starting compose2nix-wrapper script..."
fi

# Get the current directory name for both output and project name.
# For example, if you're in the "scrutiny" directory, DIR_NAME becomes "scrutiny".
DIR_NAME=$(basename "$(pwd)")
PROJECT_NAME="${DIR_NAME}"

# Set output directory and ensure it exists.
OUTPUT_DIR="/etc/nixos/containers"
if [ ! -d "$OUTPUT_DIR" ]; then
  echo "Creating output directory $OUTPUT_DIR..."
  sudo mkdir -p "$OUTPUT_DIR"
fi

# Set the output file path.
OUTPUT_FILE="${OUTPUT_DIR}/${DIR_NAME}.nix"
echo "Using directory name '${DIR_NAME}' for project name."
echo "Output file will be ${OUTPUT_FILE}"

# Run compose2nix to generate the initial Nix file.
if $DEBUG; then
  echo "DEBUG: Running compose2nix..."
fi
sudo nix --extra-experimental-features "nix-command flakes" run github:aksiksi/compose2nix -- -output "${OUTPUT_FILE}" -project "${PROJECT_NAME}"

# Full paths for required commands.
GREP="/run/current-system/sw/bin/grep"
HEAD="/run/current-system/sw/bin/head"
SED="/run/current-system/sw/bin/sed"
SORT="/run/current-system/sw/bin/sort"
UNIQ="/run/current-system/sw/bin/uniq"
MKTEMP="/run/current-system/sw/bin/mktemp"
MV="/run/current-system/sw/bin/mv"

# Remove any unsupported autoUpdate lines.
$SED -i '/autoUpdate/d' "$OUTPUT_FILE"

# Extract volume paths from the generated Nix file and build tmpfiles rules.
if $DEBUG; then
  echo "DEBUG: Extracting volume paths..."
fi
HOST_PATHS=$($GREP -o '"/[^:]*' "$OUTPUT_FILE" | $SED 's/"//g')
if $DEBUG; then
  echo "DEBUG: Found host paths:" $HOST_PATHS
fi

TMPFILES_RULES=""
for PATH in $HOST_PATHS; do
  if [[ "$PATH" == /home/* && "$PATH" != */run/* ]]; then
    USER_FROM_PATH=$($SED -E 's|/home/([^/]+)/.*|\1|' <<< "$PATH")
    DIR_PATH=$($SED "s|/home/$USER_FROM_PATH/|/home/\${config.mainUser.username}/|" <<< "$PATH")
    TMPFILES_RULES+="    \"d $DIR_PATH 0755 \${config.mainUser.username} users - -\"\n"
    if $DEBUG; then
      echo "DEBUG: Added tmpfiles rule for path: $DIR_PATH"
    fi
  fi
done

# Extract container images and build both pull service and activation script blocks.
if $DEBUG; then
  echo "DEBUG: Extracting container images..."
fi
CONTAINER_IMAGES=$($GREP -o 'image = "[^"]*"' "$OUTPUT_FILE" | $SED 's/image = "\(.*\)"/\1/')
if $DEBUG; then
  echo "DEBUG: Found container images:" $CONTAINER_IMAGES
fi

PULL_SERVICES=""
ACTIVATION_SCRIPT=""
for IMAGE in $CONTAINER_IMAGES; do
  # Derive container name: take the part after the last slash and remove any tag.
  CONTAINER_NAME=$(echo "${IMAGE##*/}" | $SED 's/:.*$//')
  SERVICE_NAME="pull-$(echo ${IMAGE##*/} | $SED 's/:/-/')-image"

  # Build the pull service block (manual pull option).
  PULL_SERVICES+="  # Auto-created image pull service\n"
  PULL_SERVICES+="  systemd.services.\"$SERVICE_NAME\" = {\n"
  PULL_SERVICES+="    description = \"Pull latest ${IMAGE##*/} image\";\n"
  PULL_SERVICES+="    path = [ pkgs.podman ];\n"
  PULL_SERVICES+="    script = ''\n"
  PULL_SERVICES+="      podman pull $IMAGE\n"
  PULL_SERVICES+="    '';\n"
  PULL_SERVICES+="    serviceConfig = {\n"
  PULL_SERVICES+="      Type = \"oneshot\";\n"
  PULL_SERVICES+="    };\n"
  PULL_SERVICES+="    wantedBy = [ \"multi-user.target\" ];\n"
  PULL_SERVICES+="  };\n\n"
  if $DEBUG; then
    echo "DEBUG: Created pull service $SERVICE_NAME for image $IMAGE"
  fi

  # Build activation script commands for each container.
  ACTIVATION_SCRIPT+="echo \"Pulling latest image for $CONTAINER_NAME...\"\n"
  ACTIVATION_SCRIPT+="\${pkgs.podman}/bin/podman pull $IMAGE || true\n"
  ACTIVATION_SCRIPT+="echo \"Done pulling for $CONTAINER_NAME.\"\n"
done

# Reassemble the output file with the additional blocks.
if $DEBUG; then
  echo "DEBUG: Adding tmpfiles rules, pull services, and activation script to $OUTPUT_FILE"
fi
$SED -i '1s/^/# Auto-generated by compose2nix-wrapper\n/' "$OUTPUT_FILE"

TMP_FILE=$($MKTEMP)
FUNC_DECL=$($GREP -E '^\{.*\}:' "$OUTPUT_FILE" || echo "{ pkgs, lib, config, ... }:")

# Write the function declaration and opening brace.
echo "$FUNC_DECL" > "$TMP_FILE"
echo "{" >> "$TMP_FILE"

# Insert tmpfiles rules if present.
if [ -n "$TMPFILES_RULES" ]; then
  echo "  # Auto-created directory rules" >> "$TMP_FILE"
  echo -e "  systemd.tmpfiles.rules = [\n${TMPFILES_RULES}  ];" >> "$TMP_FILE"
  if $DEBUG; then
    echo "DEBUG: Added tmpfiles rules."
  fi
fi

# Insert the manual pull services.
if [ -n "$PULL_SERVICES" ]; then
  echo -e "${PULL_SERVICES}" >> "$TMP_FILE"
  if $DEBUG; then
    echo "DEBUG: Added pull services."
  fi
fi

# Insert the activation script block that pulls container images on every rebuild.
if [ -n "$ACTIVATION_SCRIPT" ]; then
  echo "  # Auto-created activation script to pull container images on rebuild" >> "$TMP_FILE"
  echo "  system.activationScripts.pullContainers = ''" >> "$TMP_FILE"
  # Indent each line of the activation script by 4 spaces.
  echo -e "${ACTIVATION_SCRIPT}" | $SED 's/^/    /' >> "$TMP_FILE"
  echo "  '';" >> "$TMP_FILE"
  if $DEBUG; then
    echo "DEBUG: Added activation script for container image pulls."
  fi
fi

# Append the rest of the original file (skip the function declaration and opening brace).
$SED -n '/^{$/,${p}' "$OUTPUT_FILE" | $SED '1d' >> "$TMP_FILE"
$MV "$TMP_FILE" "$OUTPUT_FILE"
if $DEBUG; then
  echo "DEBUG: Replaced original file with updated version."
fi

# Replace any hardcoded usernames in paths with the dynamic variable.
USERNAMES=$($SED -n 's|.*/home/\([^/]*\)/.*|\1|p' "$OUTPUT_FILE" | $SORT | $UNIQ)
for USERNAME in $USERNAMES; do
  $SED -i "s|/home/$USERNAME/|/home/\${config.mainUser.username}/|g" "$OUTPUT_FILE"
  if $DEBUG; then
    echo "DEBUG: Replaced username $USERNAME with dynamic user in paths."
  fi
done

# Fix any double slashes in paths.
$SED -i 's|//docker-compose/scrutiny/|/docker-compose/scrutiny/|g' "$OUTPUT_FILE"

echo "Generated ${OUTPUT_FILE} with automatic directory creation, manual pull service, and an activation script for image pulls."
echo "Before installing, please verify the syntax is correct:"
echo "cat ${OUTPUT_FILE}"
echo "To install: sudo cp ${OUTPUT_FILE} /etc/nixos/ && sudo nixos-rebuild switch"
